% MATLAB Code
% Generated by MATLAB 9.11 and Radar Toolbox 1.1
% Generated on 14-Sep-2022 11:10:25

% All quantities are in standard units

wavelen = 0.3;							% Wavelength (m)
pwidth = 5e-07;							% Pulse width (s)
sysloss = 2;							% System losses (dB)
noisetemp = 290;						% Noise temperature (K)
rcs1=0.1;
rcs2 = 1;								% Target radar cross section (m^2)
gain = 30;								% Gain (dB)
pkpow = 5000;							% Peak transmit power (W)
snr = 16;								% SNR (dB)
tgtrng1 = radareqrng(wavelen, snr, pkpow, pwidth,'rcs', rcs1, 'gain', ...
    gain, 'loss', sysloss, 'Ts', noisetemp)
tgtrng2 = radareqrng(wavelen, snr, pkpow, pwidth,'rcs', rcs2, 'gain', ...
    gain, 'loss', sysloss, 'Ts', noisetemp)